version: '3.8'
services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: BookingAppDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: asdf1234
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - db

  check-service:
    build: ./check-service
    ports:
      - "8082:8082"
    depends_on:
      - db

  booking-service:
    build: ./booking-service
    ports:
      - "8083:8083"
    depends_on:
      - db