version: '3.8'
services:
  db:
    image: postgres:12-alpine
    env_file: .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - bookingapp-network

  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    env_file: .env
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - bookingapp-network

  check-service:
    build:
      context: .
      dockerfile: ./check-service/Dockerfile
    env_file: .env
    ports:
      - "8082:8082"
    depends_on:
      - db
      - auth-service
    networks:
      - bookingapp-network

  booking-service:
    build:
      context: .
      dockerfile: ./booking-service/Dockerfile
    env_file: .env
    ports:
      - "8083:8083"
    depends_on:
      - db
      - auth-service
      - check-service
    networks:
      - bookingapp-network

  payment-service:
    build:
      context: .
      dockerfile: ./payment-service/Dockerfile
    env_file: .env
    ports:
      - "8084:8084"
    depends_on:
      - db
      - auth-service
      - booking-service
    networks:
      - bookingapp-network

networks:
  bookingapp-network:
    driver: bridge