version: '3.8'
services:
  db:
    image: postgres:12-alpine
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - bookingapp-network

  auth-service:
    env_file:
      - .env
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - bookingapp-network

  check-service:
    env_file:
      - .env
    build: ./check-service
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
      - bookingapp-network

  booking-service:
    env_file:
      - .env
    build: ./booking-service
    ports:
      - "8083:8083"
    depends_on:
      - db
    networks:
      - bookingapp-network
networks:
  bookingapp-network:
    driver: bridge